name: buddies_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  http: ^1.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  shared_preferences: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/.
    - assets/svg/.

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat/Montserrat-Black.ttf
          weight: 900

    - family: Nunito Sans
      fonts:
        - asset: fonts/Nunito/NunitoSans_10pt-Regular.ttf
          weight: 400
        - asset: fonts/Nunito/NunitoSans_10pt-ExtraLight.ttf
          weight: 200
        - asset: fonts/Nunito/NunitoSans_10pt-Light.ttf
          weight: 300
        - asset: fonts/Nunito/NunitoSans_10pt-Medium.ttf
          weight: 500
        - asset: fonts/Nunito/NunitoSans_10pt-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito/NunitoSans_10pt-Bold.ttf
          weight: 700
        - asset: fonts/Nunito/NunitoSans_10pt-ExtraBold.ttf
          weight: 800
        - asset: fonts/Nunito/NunitoSans_10pt-Black.ttf
          weight: 900
    - family: Solitreo
      fonts:
        - asset: fonts/Solitreo-Regular.ttf
