// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABAce2MBET27zgPE5qFzF86-plT-QLRg4',
    appId: '1:742890676193:web:420e03fa72604985a27ca0',
    messagingSenderId: '742890676193',
    projectId: 'buddies-app-df34b',
    authDomain: 'buddies-app-df34b.firebaseapp.com',
    storageBucket: 'buddies-app-df34b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaLhnWLHVQknJgO6b7hv404pKU-NjggWo',
    appId: '1:742890676193:android:9f6006d63068a2eea27ca0',
    messagingSenderId: '742890676193',
    projectId: 'buddies-app-df34b',
    storageBucket: 'buddies-app-df34b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYi6DD3gAMCzJQdEsUVuCQB8NeG10Af2w',
    appId: '1:742890676193:ios:1bfb38ce9824b804a27ca0',
    messagingSenderId: '742890676193',
    projectId: 'buddies-app-df34b',
    storageBucket: 'buddies-app-df34b.appspot.com',
    iosClientId: '742890676193-2qg7rnv5hdgmvef5hi6ui3nkv6lh9atf.apps.googleusercontent.com',
    iosBundleId: 'com.example.buddiesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYi6DD3gAMCzJQdEsUVuCQB8NeG10Af2w',
    appId: '1:742890676193:ios:b17e7bd64b874794a27ca0',
    messagingSenderId: '742890676193',
    projectId: 'buddies-app-df34b',
    storageBucket: 'buddies-app-df34b.appspot.com',
    iosClientId: '742890676193-fc39729h4o9mf80n83ncbm4t7b0jkr0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.buddiesApp.RunnerTests',
  );
}
